swagger: "2.0"
info:
  description: "TM Forum Intent API"
  version: "0.0.9"
  title: "TMF Intent API"
  termsOfService: "http://tmforum.swagger.io/terms/"
  contact:
    email: "james.o.sullivan@huawei.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "tmforum.swagger.io"
basePath: "/v1"
tags:
- name: "intent"
  description: "Intent Lifecycle Management"
  externalDocs:
    description: "Find out more"
    url: "http://tmforum.swagger.io"
schemes:
- "https"
- "http"
paths:
  /intent:
    post:
      tags:
      - "intent"
      summary: "Set an intent"
      description: ""
      operationId: "setIntent"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Intent object that needs to be set"
        required: true
        schema:
          $ref: "#/definitions/Intent"
      responses:
        "405":
          description: "Invalid input"
      security:
      - intentapi_auth:
        - "write:intent"
        - "read:intent"
    put:
      tags:
      - "intent"
      summary: "Set an existing intent"
      description: ""
      operationId: "updateIntent"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Intent object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/Intent"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Intent not found"
        "405":
          description: "Validation exception"
      security:
      - intentapi_auth:
        - "write:intent"
        - "read:intent"
  /intent/list:
    get:
      tags:
      - "intent"
      summary: "List all intents"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "listIntents"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Intent"
        "400":
          description: "Invalid status value"
      security:
      - intentapi_auth:
        - "write:intent"
        - "read:intent"
  /intent/findByStatus:
    get:
      tags:
      - "intent"
      summary: "Finds Intent by status"
      description: "Multiple status values can be provided with comma separated strings"
      operationId: "findIntentsByStatus"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "status"
        in: "query"
        description: "Status values that need to be considered for filter"
        required: true
        type: "array"
        items:
          type: "string"
          enum:
          - "ok"
          - "inViolation"
          - "all"
          default: "ok"
        collectionFormat: "multi"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Intent"
        "400":
          description: "Invalid status value"
      security:
      - intentapi_auth:
        - "write:intent"
        - "read:intent"
  /intent/{intentId}:
    get:
      tags:
      - "intent"
      summary: "Find Intent by ID"
      description: "Returns a single intent"
      operationId: "getIntentById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "intentId"
        in: "path"
        description: "ID of intent to return"
        required: true
        type: string
        format: uuid
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Intent"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Intent not found"
      security:
      - intentapi_auth:
        - "write:intent"
        - "read:intent"
    delete:
      tags:
      - "intent"
      summary: "Removes or retires an intent"
      description: ""
      operationId: "deleteIntent"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "intentId"
        in: "path"
        description: "Intent id to delete"
        required: true
        type: string
        format: uuid
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Intent not found"
      security:
      - intentapi_auth:
        - "write:intent"
        - "read:intent"
securityDefinitions:
  intentapi_auth:
    type: "oauth2"
    authorizationUrl: "http://tmforum.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:intent: "modify intent"
      read:intent: "read intent"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Intent:
    type: "object"
    required:
      - intentId
      - createTime
      - lastModificationTime
    properties:
      intentId:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      createTime:
        type: string
        example: "2020-08-29T09:12:33.001Z"
      lastModificationTime:
        type: string
        example: "2020-08-29T09:12:33.001Z"
    xml:
      name: "Intent"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
